# Generated by Django 4.0.4 on 2022-05-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
